package timecalculator;
import java.awt.Toolkit;
import java.awt.Window.Type;

import javax.swing.AbstractButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;

import java.awt.Font;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pc
 */
public class Timecalculator extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected AbstractButton textField;
	/**
     * Creates new form Interface
     */
    public Timecalculator() {
		getContentPane().setBackground(UIManager.getColor("Button.light"));
    	setTitle("Time calculator\r\n");
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\riche\\OneDrive\\Desktop\\360_F_493213396_sSzFzox16pCO1gXCsXiGGvhwnGe5sVLJ.jpg"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBackground(new Color(204, 255, 204));
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(null);
        jButton2 = new javax.swing.JButton();
        jButton2.setForeground(new Color(220, 20, 60));
        jButton3 = new javax.swing.JButton();
        jButton3.setForeground(new Color(220, 20, 60));
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(100, 149, 237));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(288)
        			.addComponent(jLabel1)
        			.addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jComboBox1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jComboBox1.setModel(new DefaultComboBoxModel(new String[] {"Hour", "Second", "Minute", "Day", "Weeks", "Year"}));

        jComboBox2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jComboBox2.setModel(new DefaultComboBoxModel(new String[] {"Minute", "Second", "Hour", "Day", "weeks", "year"}));

        jTextField1.setFont(new Font("Dialog", Font.BOLD, 25)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 68, 169)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new Color(204, 255, 204));
        jTextField2.setFont(new Font("Dialog", Font.BOLD, 25)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 68, 169)));

        jButton1.setBackground(new Color(100, 149, 237));
        jButton1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jButton1.setForeground(new Color(0, 0, 0));
        jButton1.setText("Calculate");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(230, 231, 250));
        jButton2.setFont(new Font("Dialog", Font.BOLD, 20)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(230, 231, 250));
        jButton3.setFont(new Font("Dialog", Font.BOLD, 20)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Project by: Abdullah Al Rahman   ID: 0322310105101003");
        
        JButton btn7 = new JButton("7");
        btn7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		String number=jTextField1.getText()+btn7.getText();
				jTextField1.setText(number);
        	}
        });
        btn7.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn8 = new JButton("8");
        btn8.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn8.getText();
				jTextField1.setText(number);
        	}
        }
        );
        btn8.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn9 = new JButton("9");
        btn9.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn9.getText();
				jTextField1.setText(number);
        	}
        });
        btn9.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn4 = new JButton("4");
        btn4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn4.getText();
				jTextField1.setText(number);
        	}
        });
        btn4.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn5 = new JButton("5");
        btn5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn5.getText();
				jTextField1.setText(number);
        	}
        });
        btn5.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn6 = new JButton("6");
        btn6.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn6.getText();
				jTextField1.setText(number);
        	}
        });
        btn6.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn1 = new JButton("1");
        btn1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn1.getText();
				jTextField1.setText(number);
        	}
        });
        btn1.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn2 = new JButton("2");
        btn2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn2.getText();
				jTextField1.setText(number);
        	}
        });
        btn2.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn3 = new JButton("3");
        btn3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn3.getText();
				jTextField1.setText(number);
        	}
        });
        btn3.setFont(new Font("Tahoma", Font.BOLD, 22));
        
        btn0 = new JButton("0");
        btn0.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String number=jTextField1.getText()+btn0.getText();
				jTextField1.setText(number);
        	}
        });
        btn0.setFont(new Font("Tahoma", Font.BOLD, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 409, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(73)
        			.addComponent(btn6, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btn1, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btn2, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btn3, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        			.addGap(27)
        			.addComponent(btn0, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(152, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(btn7, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        							.addGap(56))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jComboBox1, 0, 183, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btn8, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
        							.addGap(28)
        							.addComponent(btn9, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(btn4, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(btn5, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(80)
        							.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
        							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(216)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jButton1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        				.addComponent(jLabel2, Alignment.LEADING))
        			.addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(7)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(29)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btn5, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn4, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn9, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn8, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        				.addComponent(btn7, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btn0, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btn3, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn2, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn1, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn6, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(26)
        			.addComponent(jLabel2)
        			.addGap(21))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String box1=(String)jComboBox1.getSelectedItem();
      String box2=(String)jComboBox2.getSelectedItem();
     
       if(box1.equals("Hour") && box2.equals("Minute"))
       {
           double h = Double.parseDouble(jTextField1.getText());
           
           double m = (double)(h*60);
           
           jTextField2.setText(String.valueOf(m));
       }
       else if(box1.equals("Hour") && box2.equals("Second"))
       {
           double h = Double.parseDouble(jTextField1.getText());
           
           double s = (double)(h*3600 );
           
           jTextField2.setText(String.valueOf(s));
       }
       else if(box1.equals("Hour") && box2.equals("Hour"))
       {
           double h = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(h));
       }
       else if(box1.equals("Hour") && box2.equals("Day"))
       {
           double h = Double.parseDouble(jTextField1.getText());
           
           double d = (double)(h/24 );
           
           jTextField2.setText(String.valueOf(d));
       }
       else if(box1.equals("Hour") && box2.equals("Weeks"))
       {
           double h = Double.parseDouble(jTextField1.getText());
           
           double w = (double)(h/168);
           
           jTextField2.setText(String.valueOf(w));
       }

       if(box1.equals("Minute") && box2.equals("Second"))
       {
           double m = Double.parseDouble(jTextField1.getText());
           
           double s = (double)(m*60);
           
           jTextField2.setText(String.valueOf(s));
       }
       else if(box1.equals("Minute") && box2.equals("Hour]"))
       {
           double m = Double.parseDouble(jTextField1.getText());
           
           double h = (double)(m/60);
           
           jTextField2.setText(String.valueOf(h));
       }
       else if(box1.equals("Minute") && box2.equals("Minute"))
       {
           double m = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(m));
       }
       

       if(box1.equals("Second") && box2.equals("Minute"))
       {
           double s = Double.parseDouble(jTextField1.getText());
           
           double m = (double)(s/60);
           
           jTextField2.setText(String.valueOf(m));
       }
       else if(box1.equals("Second") && box2.equals("Hour"))
       {
           double s = Double.parseDouble(jTextField1.getText());
           
           double h = (double)(s/3600);
           
           jTextField2.setText(String.valueOf(h));
       }
       else if(box1.equals("Second") && box2.equals("Second"))
       {
           double s = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(s));
       }
       if(box1.equals("Day") && box2.equals("Hour"))
       {
           double d = Double.parseDouble(jTextField1.getText());
           
           double h = (double)(d*24);
           
           jTextField2.setText(String.valueOf(h));
       }
       else if(box1.equals("Day") && box2.equals("Minute"))
       {
           double d = Double.parseDouble(jTextField1.getText());
           
           double m = (double)(d*1440);
           
           jTextField2.setText(String.valueOf(m));
       }
       else if(box1.equals("Day") && box2.equals("Second"))
       {
           double d = Double.parseDouble(jTextField1.getText());
           
           double s = (double)(d*86400);
           
           jTextField2.setText(String.valueOf(s));
       }
       else if(box1.equals("Day") && box2.equals("Day"))
       {
           double d = Double.parseDouble(jTextField1.getText());
         
           jTextField2.setText(String.valueOf(d));
       }
       else if(box1.equals("Day") && box2.equals("Weeks"))
       {
           double d = Double.parseDouble(jTextField1.getText());
           
           double w = (double)(d*7);
           
           jTextField2.setText(String.valueOf(w));
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timecalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private JButton btn8;
    private JButton btn9;
    private JButton btn4;
    private JButton btn5;
    private JButton btn6;
    private JButton btn1;
    private JButton btn2;
    private JButton btn3;
    private JButton btn0;
}
